name: Services application

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            mariadb:
                image: mariadb:latest
                ports:
                    - 3306
                env:
                    MYSQL_USER: root
                    MYSQL_DATABASE: db1
                    MYSQL_ROOT_PASSWORD: 123456
                options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

        env:
            databaseUser: root
            databasePassword: 123456
            databaseDBName: db1
            databaseHost: localhost
            port: 8080
            host: 0.0.0.0

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Instalação de Dependencias
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt;
            - name: Execução de Teste de unidades
              run: |
                  python -m unittest discover ./tests
