name: Services application

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup MariaDb
              uses: getong/mariadb-action@master
              with:
                  mysql database: db1
                  mysql root password: 123456

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Instalação de Dependencias
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt;

            - name: Execução de Teste de unidades
              run: |
                  python -m unittest tests.test_CheckUserDataTest
